1st chapter - Overview
vishvAsa/kalpAntaram pull request #143
Opened 2022-09-03 17:47 UTC by Vinayak-Seenivasan

First 13 pages done. Still 5 more pages and footnotes are yet to be done

2022-09-04 00:10 UTC, vvasuki requested changes

2022-09-04 00:10 UTC, vvasuki commented on kANe/v2p1/01_Topics_of_dharmashAstra.md
> ++++ title = "01 Topics of Dharmaśāstra"
Please revert this line. It is important (for html rendering) that it remain as it was earlier.

2022-09-19 14:22 UTC, Vinayak-Seenivasan commented
I will update the changes in today's pull request

2022-09-19 14:22 UTC, closed without merging

2022-09-19 14:22 UTC, Vinayak-Seenivasan reviewed
Please find the changes