Content
vishvAsa/kalpAntaram pull request #196
Opened 2022-12-02 14:24 UTC by 9108172485

2022-12-02 14:33 UTC, vvasuki requested changes

2022-12-02 14:33 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
>  1957
एता निरर्थकपङ्क्तयो निष्कासनीयाः।

2022-12-02 14:33 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +    **धर्म पद्धतिः ॥**
पङ्क्तीनाम् आदौ रिक्तस्थानानि न स्युः।

2022-12-02 14:33 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +मुख्यो धर्मः स्मृतिषु विहितो भर्तृशुश्रूषणं हि
यदि भिन्नपङ्क्तिषु विन्यास इष्टः, पङ्क्तेर् अन्ते रिक्तस्थानद्वयं स्यात्।

2022-12-02 14:35 UTC, 9108172485 commented
Astu. .

On Fri, 2 Dec, 2022, 8:03 pm Vishvas Vasuki विश्वासः, <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In strI-dharma-paddhatiH/mUlam.md
> <https://github.com/vishvAsa/kalpAntaram/pull/196#discussion_r1038201830>:
>
> > @@ -18,417 +18,301 @@ Source: [Arch](https://archive.org/details/streedharmapaddathi/page/39/mode/2up)
>  31,  ,
>  1957
>
> एता निरर्थकपङ्क्तयो निष्कासनीयाः।
> ------------------------------
>
> In strI-dharma-paddhatiH/mUlam.md
> <https://github.com/vishvAsa/kalpAntaram/pull/196#discussion_r1038202098>:
>
> > @@ -18,417 +18,301 @@ Source: [Arch](https://archive.org/details/streedharmapaddathi/page/39/mode/2up)
>  31,  ,
>  1957
>  3
> -|| त्र्यंबकरायमखिनिबद्धा स्त्रीणामावश्यिका
> -धर्म पद्धतिः ॥
> -मुख्यो धर्मः स्मृतिषु विहितो भर्तृशुश्रूषणं हि _स्त्रीणामेतत्पितुरनुमतं कार्यमित्याकलय्य । तत्कुर्वाणाऽभजत वपुपो भर्तुर, हिमाद्रेः
> -कन्या सा मे दिशतु सततं धर्ममार्गप्रवृत्तिम् ॥१॥ लोकस्यानुजिघृक्षया स्मृतिपुराणोक्तया पितुश्चाज्ञया __ शुश्रूषां परमां विधाय सुचिरं भर्तुः प्रसादार्थिनी । देहाद्वैतमवाप या भगवतश्चन्द्रार्धचूडामणेः
> +||
> +त्र्यंबकरायमखिनिबद्धा स्त्रीणामावश्यिका
> +    **धर्म पद्धतिः ॥**
>
> पङ्क्तीनाम् आदौ रिक्तस्थानानि न स्युः।
> ------------------------------
>
> In strI-dharma-paddhatiH/mUlam.md
> <https://github.com/vishvAsa/kalpAntaram/pull/196#discussion_r1038202645>:
>
> > @@ -18,417 +18,301 @@ Source: [Arch](https://archive.org/details/streedharmapaddathi/page/39/mode/2up)
>  31,  ,
>  1957
>  3
> -|| त्र्यंबकरायमखिनिबद्धा स्त्रीणामावश्यिका
> -धर्म पद्धतिः ॥
> -मुख्यो धर्मः स्मृतिषु विहितो भर्तृशुश्रूषणं हि _स्त्रीणामेतत्पितुरनुमतं कार्यमित्याकलय्य । तत्कुर्वाणाऽभजत वपुपो भर्तुर, हिमाद्रेः
> -कन्या सा मे दिशतु सततं धर्ममार्गप्रवृत्तिम् ॥१॥ लोकस्यानुजिघृक्षया स्मृतिपुराणोक्तया पितुश्चाज्ञया __ शुश्रूषां परमां विधाय सुचिरं भर्तुः प्रसादार्थिनी । देहाद्वैतमवाप या भगवतश्चन्द्रार्धचूडामणेः
> +||
> +त्र्यंबकरायमखिनिबद्धा स्त्रीणामावश्यिका
> +    **धर्म पद्धतिः ॥**
> +मुख्यो धर्मः स्मृतिषु विहितो भर्तृशुश्रूषणं हि
>
> यदि भिन्नपङ्क्तिषु विन्यास इष्टः, पङ्क्तेर् अन्ते रिक्तस्थानद्वयं स्यात्।
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/kalpAntaram/pull/196#pullrequestreview-1202587966>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4PB2NDOAHXHRVCXDW3FSCDWLICD7ANCNFSM6AAAAAASR7BKZU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-02 14:47 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +    **धर्म पद्धतिः ॥**
kutra?

2022-12-02 14:50 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +मुख्यो धर्मः स्मृतिषु विहितो भर्तृशुश्रूषणं हि
na jnaatam kim iti

2022-12-05 11:13 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
>  1957
निष्काशितम्।

2022-12-05 11:16 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +    **धर्म पद्धतिः ॥**
सम्यक् कृतम्

2022-12-08 09:15 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +<<<<<<< HEAD
टॆलिग्राम्य् उक्तया रीत्येतादृश्यः पङ्क्तयो निवारणीयाः। विनिवार्येह सूचयतु।

2022-12-10 09:14 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +त्र्यंबकरायमखिनिबद्धा स्त्रीणामावश्यिका|
`|`चिह्नम् इहाधिकम्।

2022-12-10 09:15 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +>श्रीः कृत्वेह वपुः कान्तं गोमध्येषु विवेश ह ।
उद्धरणारम्भात् पूर्वं रिक्तपङ्क्तिर् अस्तु। एवञ्च `> ` इति रिक्तावकाशसहितम् (space) अस्तु। एवं सर्वत्र समीकृत्यात्र +उररीकरोतु।

2022-12-10 09:16 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +पूजोपकरणं सर्वमनुक्तं साधयेत्स्वयम् ॥ इति स्कान्दवचनात्॥
`इति स्कान्दवचनात्॥`  इति उद्धरणांशाद् बहिर् भवेत्। एवम् अन्यत्र । सर्वत्र समीकृत्य +अत्र प्रतिवदेत्।

2022-12-10 09:17 UTC, vvasuki requested changes

2022-12-10 09:17 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +नैकाकिनी क्वचिद्भूया न्न नग्ना स्नाति वै क्वचिदिति।।६६।।
असमीचीनम् अत्र।

2022-12-10 09:17 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +यत्र पुंसः सचेलं स्यात् स्नानं तत्र सुवासिनी ।
उद्धरणचिह्नम्?

2022-12-19 09:20 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +यत्र पुंसः सचेलं स्यात् स्नानं तत्र सुवासिनी ।
कुत्र इति न ज्ञातम्

2022-12-19 10:16 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +यत्र पुंसः सचेलं स्यात् स्नानं तत्र सुवासिनी ।
"स्मृत्यर्थसारे विशेष उक्तः॥" इति भिन्नः paragraph-भागः स्यात्। ततः परम् "यत्र पुंसः सचेलं" इत्युद्धरणम् आरभते। तद् अपि भिन्नः paragraph-भागः स्यात्, तत्र चादौ उद्दरणचिह्नम् इष्यते। एवम् अन्यत्रापि परिष्कृतपङ्क्तिषु तद् एव शोधनं साधयित्वा सूचयतु।

2022-12-27 10:44 UTC, vvasuki requested changes
नमामि - बहवो दोषा विद्यन्ते।  अग्रे नैकाम् अपि पङ्क्तिं शोधयेद् यावद् इमे दोषा न निवारिताः, मया चानुज्ञातम्। कृपयास्य पुनः परीक्षणे शोधने च प्रयतताम्।

2022-12-27 10:44 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +तत्र, "शौचाचारविहीनस्य समस्ता निष्फलाः क्रियाः।"
पुनर् एमे पङ्क्ती उपरि दृश्येते।

2022-12-27 10:44 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +तत्र पुरुषाणामामौंजीब्न्न्धनात् शास्त्रेण नियमाः न विधीयन्ते मौंजीबंधनप्रभृत्येव नियमाः॥
अत्र टङ्कनदोषो मार्जनीयः।

2022-12-27 10:44 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +> मुख्यो धर्मः स्मृतिषु विहितो भर्तृशुश्रूषणं हि
नैतद् उद्धरणं खलु। मङ्गलश्लोका अस्यैव ग्रन्थस्य। तर्हि +उद्धरणचिह्नं न स्यात्।

2022-12-27 10:44 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +> येषामाचरणेन कीर्तिरतुला भूयस्सुखं चैहिकं
नैतद् उद्धरणं खलु। मङ्गलश्लोका अस्यैव ग्रन्थस्य। तर्हि +उद्धरणचिह्नं न स्यात्।

2022-12-27 10:44 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +उपनीय गुरुः शिष्यं शिक्षयेच्छौचमादितः ।
अत्रोद्धरणचिह्नं युज्यते।

2022-12-27 10:44 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +>सुप्ते पश्चाच्च या शेते पूर्वमेव प्रबुध्यते ।
उद्धरणचिह्नात् प्राग् रिक्तपङ्क्तिर् इष्यते। कथम् इति सुज्ञायानुवर्तताम्। https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/

2022-12-28 01:07 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +तत्र, "शौचाचारविहीनस्य समस्ता निष्फलाः क्रियाः।"
निश्काशितम्।

2022-12-28 01:07 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +तत्र पुरुषाणामामौंजीब्न्न्धनात् शास्त्रेण नियमाः न विधीयन्ते मौंजीबंधनप्रभृत्येव नियमाः॥
मार्जितम्।

2022-12-28 01:08 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +> मुख्यो धर्मः स्मृतिषु विहितो भर्तृशुश्रूषणं हि
आम्।

2022-12-28 01:08 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +उपनीय गुरुः शिष्यं शिक्षयेच्छौचमादितः ।
स्थापितम्।

2022-12-28 01:09 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +>सुप्ते पश्चाच्च या शेते पूर्वमेव प्रबुध्यते ।
आम्।

2022-12-28 01:10 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +>सुप्ते पश्चाच्च या शेते पूर्वमेव प्रबुध्यते ।
चिह्ना अनन्तरं खलु रिक्तस्थानम्?

2022-12-28 01:12 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +>सुप्ते पश्चाच्च या शेते पूर्वमेव प्रबुध्यते ।
चिह्नायाः अनन्तरं रिक्तस्थानं भवेत् खलु?

2022-12-28 01:41 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +इति वचनात् इतरधर्मसाफल्यसिध्यर्थं शौचाचारस्यावश्यकत्वमिति आदौ आचारो निरूप्यते ॥
अत्र टङ्कनदोषो मार्जनीयः।

2022-12-28 01:41 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +’नास्य कर्म नियच्छन्ति किंचिदामौजिबंधनात्' ।
मौजि?

2022-12-28 01:41 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +>सुप्ते पश्चाच्च या शेते पूर्वमेव प्रबुध्यते ।
riktā paṅktiḥ = empty line
riktaṁ sthānam = space

https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/ ityatra yathā darśitaṁ, dvayam api syāt pūrva-parayōḥ

2022-12-29 03:55 UTC, vvasuki requested changes

2022-12-29 03:55 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +अथ गोसेवनम्-भारते ।।
अथ गोसेवनम् - भारते । (पदभेदे रिक्तस्थाननिवेशनं स्यात्। अन्यथा समासभ्रमो भवेत्। )

2023-01-07 04:45 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +तत्र, "शौचाचारविहीनस्य समस्ता निष्फलाः क्रियाः।"
समीकृतम्।

2023-01-07 04:46 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +> येषामाचरणेन कीर्तिरतुला भूयस्सुखं चैहिकं
निश्काशितम्।

2023-01-07 04:46 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +इति वचनात् इतरधर्मसाफल्यसिध्यर्थं शौचाचारस्यावश्यकत्वमिति आदौ आचारो निरूप्यते ॥
मार्जितम्।

2023-01-07 04:51 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +<<<<<<< HEAD
साधितम्।

2023-01-07 04:51 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +नैकाकिनी क्वचिद्भूया न्न नग्ना स्नाति वै क्वचिदिति।।६६।।
समीकृतम्।

2023-01-07 05:27 UTC, vvasuki commented
महोदये, "Close with comment" इति, "Close" इति वा कीलकं न नोदनीयम्।

2023-01-07 05:29 UTC, 9108172485 commented
Astu

On Sat, 7 Jan, 2023, 10:57 am Vishvas Vasuki विश्वासः, <
***@***.***> wrote:

> महोदये, "Close with comment" इति, "Close" इति वा कीलकं न नोदनीयम्।
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/kalpAntaram/pull/196#issuecomment-1374383796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4PB2NFN6PHURC4SUA72DSDWRD5EZANCNFSM6AAAAAASR7BKZU>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-01-07 06:08 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +> तत्र, "शौचाचारविहीनस्य समस्ता निष्फलाः क्रियाः"।
"तत्र" इति शब्दो नोद्धरणाङ्गम्। तर्हि >-पङ्क्तौ न स्याद् एव। 

उद्धरण-भागस्यादाव् अन्ते च रिक्तपङ्क्तिस् स्याद् एव। एवं सर्वत्र शोधयतु।

2023-01-10 02:39 UTC, 9108172485 commented on strI-dharma-paddhatiH/mUlam.md
> +> तत्र, "शौचाचारविहीनस्य समस्ता निष्फलाः क्रियाः"।
समीकृतम्।

2023-01-13 04:50 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +> तत्र, "शौचाचारविहीनस्य समस्ता निष्फलाः क्रियाः"।
daṇḍa uddharaṇāgatvēna sthāpayatu, athavā niṣkāsayatu. yathā - 

तत्र, "शौचाचारविहीनस्य समस्ता निष्फलाः क्रियाः"  
इति वचनात् इतरधर्मसाफल्यसिध्यर्थं शौचाचारस्यावश्यकत्वमिति आदौ आचारो निरूप्यते ॥

(vākyamadhyē daṇḍo na yujyatē. )

2023-01-13 04:50 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +त्र्यंबकरायमखिनिबद्धा स्त्रीणामावश्यिका|
iha smāraṇam

2023-01-13 04:57 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +’नास्य कर्म नियच्छन्ति किंचिदामौंजिबंधनात्' ।
https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/Quotes/ ityatrōktayā rītyā +uddharaṇa vinyāsō nāsti. kr̥payā ’vagatya, ētāvat parivartitāsu paṅktiṣu sarvatra śōdhayatu.

2023-01-13 04:58 UTC, vvasuki commented on strI-dharma-paddhatiH/mUlam.md
> +स्त्रीणां धर्माः कतिचन मया प्रायशस्सारभूताः
https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/Spacing_paragraph-vivekaH/ ityatrōktayā rītyā ’ntē riktasthānadvayaṁ nāsti. kr̥payā niyamān avagatya,  ētāvat parivartitāsu paṅktiṣu sarvatra śōdhayatu.

2023-02-11 06:31 UTC, vvasuki commented
अत्र सद्यः महोदया नियतरीत्या दक्षतया च कार्यं साधयितुं न शक्नोतीति भाति। तेन यथाप्राप्तं स्वीकृत्य कार्यम् अन्यस्मा अर्पयामि।

2023-02-11 06:31 UTC, merged