Content
vishvAsa/kalpAntaram pull request #197
Opened 2022-12-02 14:49 UTC by chandramoulikalyan

2022-12-02 15:12 UTC, vvasuki requested changes

2022-12-02 15:12 UTC, vvasuki commented on sAmrAjya-nibandhanam.md
> +mmxcjadbkdh.leekqd
किमेतद् भोः - निवारयतु।

2022-12-02 15:12 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
>  राजकीय-संस्कृतपाठशाला-सरस्वती-भवनोपाध्यक्षेण साहित्याचार्य-पदालङ्कृतेन श्रीमता नारायण शास्त्रिखिस्तेशर्मणा संस्कृतः ।
नारायण-शास्त्रि-खिस्ते-शर्मणा 

इति लिखतु।

2022-12-02 15:12 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +अद्यत्वे समुपलभ्यमानेषु शूद्रेतिकर्तव्यताप्रतिपादकेषु धर्मशास्त्रनिबन्धेषु प्रायः प्रथमोऽयमनुभाविनां तादृशनिवन्धान्तराणामुपजीव्यभूत इति प्रतिभाति । तात्कालिकहरिचरणप्रसूतवर्णवंशावतंस दाक्षिणत्यनरपति प
अत्र paragraph-भेदे सति रिक्तपङ्क्तिः (empty line) इति स्थापनीया

2022-12-02 15:12 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +आसाद्य प्रथमं त्रिवर्गफलदां वेणीं त्रिवेणीच्छलात्
पङ्क्तिभेदं कल्पयितुं रिक्तस्थानद्वयम् पङ्क्तेर् अन्ते स्थापनीयम्।

2022-12-02 15:12 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
मध्ये `-`निवेशनम् मयैव कृतम्। तद् रक्ष्यताम्। एवं सर्वत्र।

2022-12-03 02:21 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
>  राजकीय-संस्कृतपाठशाला-सरस्वती-भवनोपाध्यक्षेण साहित्याचार्य-पदालङ्कृतेन श्रीमता नारायण शास्त्रिखिस्तेशर्मणा संस्कृतः ।
अस्तु सम्यक् क्रियते

2022-12-03 02:27 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +अद्यत्वे समुपलभ्यमानेषु शूद्रेतिकर्तव्यताप्रतिपादकेषु धर्मशास्त्रनिबन्धेषु प्रायः प्रथमोऽयमनुभाविनां तादृशनिवन्धान्तराणामुपजीव्यभूत इति प्रतिभाति । तात्कालिकहरिचरणप्रसूतवर्णवंशावतंस दाक्षिणत्यनरपति प
अस्तु दीयते

2022-12-03 02:28 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +आसाद्य प्रथमं त्रिवर्गफलदां वेणीं त्रिवेणीच्छलात्
अस्तु स्थपितम्..

2022-12-03 02:29 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +आसाद्य प्रथमं त्रिवर्गफलदां वेणीं त्रिवेणीच्छलात्
स्थापितन्*

2022-12-03 03:08 UTC, chandramoulikalyan commented on sAmrAjya-nibandhanam.md
> +mmxcjadbkdh.leekqd
निवारितम्

2022-12-03 03:08 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
अस्तु

2022-12-03 03:12 UTC, vvasuki requested changes

2022-12-03 03:12 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +विद्वत्कृपाकामुकः, काशी ३१-३-३३०
पङ्क्तेर् अन्ते रिक्तस्थानद्वयं स्यात्।

2022-12-03 03:12 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
`-`प्रयोगो यथापूर्वं कृतो न दृश्यते।

2022-12-03 03:12 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +अनिन्द्येषु विवाहेषु पुत्राः संतानवर्द्धनाः ॥ इति ।
इति-शब्दो नास्त्युद्धाराङ्गम्। पादशो विभागोऽपि वरो रक्षणीयः। यथापूर्वं करोत्वत्र।

2022-12-03 03:14 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
>  श्रीमत्-सर्वतन्त्र-स्वतन्त्र विद्वद्-वर-श्रीशेष-कृष्ण-निर्मितः शूद्राचार-शिरोमणिः
श्रीमत्-सर्वतन्त्र-स्वतन्त्र-

2022-12-03 03:14 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
अस्तु

2022-12-03 03:27 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
सद्यः कृतः

2022-12-03 03:29 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +विद्वत्कृपाकामुकः, काशी ३१-३-३३०
अस्तु दत्तम्

2022-12-03 03:33 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +अनिन्द्येषु विवाहेषु पुत्राः संतानवर्द्धनाः ॥ इति ।
यथापूर्वं कृतम्

2022-12-03 03:33 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
>  श्रीमत्-सर्वतन्त्र-स्वतन्त्र विद्वद्-वर-श्रीशेष-कृष्ण-निर्मितः शूद्राचार-शिरोमणिः
किम्?

2022-12-03 04:08 UTC, vvasuki requested changes

2022-12-03 04:08 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
अत्र कृतः - अन्यत्र न। https://github.com/vishvAsa/kalpAntaram/pull/197/files इत्यत्र पश्यतु - "तत्-सङ्कर-शङ्कि-मानसः" इति पूर्वम् अवर्तत।  सर्वत्रायं `-`-अपाकरणदोषो निवारणीयः।

2022-12-03 04:08 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
>  श्रीमत्-सर्वतन्त्र-स्वतन्त्र विद्वद्-वर-श्रीशेष-कृष्ण-निर्मितः शूद्राचार-शिरोमणिः
समस्तपदे रिक्तस्थानं न स्याद् इत्य् उक्तं खलु।

2022-12-03 04:11 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +अनिन्द्येषु विवाहेषु पुत्राः संतानवर्द्धनाः ॥ इति ।
न कृतम्। " पुत्राः संतानवर्द्धनाः ॥ " इति पादो ऽवर्तत। भवता ऽन्यथा विन्यस्तम्।

2022-12-03 04:30 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +अनिन्द्येषु विवाहेषु पुत्राः संतानवर्द्धनाः ॥ इति ।
इदानीम्?

2022-12-03 04:31 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
>  श्रीमत्-सर्वतन्त्र-स्वतन्त्र विद्वद्-वर-श्रीशेष-कृष्ण-निर्मितः शूद्राचार-शिरोमणिः
इदानीम्

2022-12-03 04:31 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
करोमि

2022-12-03 04:36 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
साधु - कृत्वा, रक्षित्वा, "कृतम्" इति सूचयत्व् अत्र।

2022-12-03 06:03 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> -आसाद्य प्रथमं त्रिवर्ग-फलदां वेणी त्रिवेणीच्छलात्
कृतम्

2022-12-03 06:08 UTC, vvasuki requested changes

2022-12-03 06:08 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +> ब्रह्म-क्षत्रिय-विट्शू-शूद्रा
किम् एतत् "विट्शू-शूद्रा  " - copy paste करणम् एव वरं स्यात् …

2022-12-03 06:08 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +> "लोकानां तु स सृष्ट्यर्थं मुखबाहूरुपादतः। ब्राह्मणं क्षत्रियं वैश्यं शूद्रं च निरवर्त्तयदत्” ।
`-`चिह्नं यथापूर्वम्

2022-12-03 06:08 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +कथं तर्हि नारद-वसिष्ठ-विश्वामित्रादीनामयोनिजानां ब्राह्मणत्वम् । तेषां सवर्णविन्ना+++(=विवाहिता)+++ऽनुत्पन्नत्वात् ।
`-`चिह्नं यथापूर्वम्

2022-12-03 06:08 UTC, vvasuki commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +सर्वसंग्राहकं तु षट्क-कर्म-प्रयोजकीभूताऽदृष्टविशेषोपगृहीतत्वम्। न तु तत्प्रवृत्त्यङ्गम्। अदृष्टादेरतीन्द्रियत्वात् । अत एव विन्नास्वेष विधिः स्मृत इत्युपसंहारोऽपि समञ्जसः ।
किम् एतत् षट्क-

2022-12-03 07:00 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +> ब्रह्म-क्षत्रिय-विट्शू-शूद्रा
कृतम्

2022-12-03 07:03 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +> "लोकानां तु स सृष्ट्यर्थं मुखबाहूरुपादतः। ब्राह्मणं क्षत्रियं वैश्यं शूद्रं च निरवर्त्तयदत्” ।
कृतम्

2022-12-03 07:07 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +सर्वसंग्राहकं तु षट्क-कर्म-प्रयोजकीभूताऽदृष्टविशेषोपगृहीतत्वम्। न तु तत्प्रवृत्त्यङ्गम्। अदृष्टादेरतीन्द्रियत्वात् । अत एव विन्नास्वेष विधिः स्मृत इत्युपसंहारोऽपि समञ्जसः ।
सम्यक् कृतम्

2022-12-03 07:08 UTC, chandramoulikalyan commented on shUdra-dharmaH/shUdrAchAra-shiromaNiH.md
> +कथं तर्हि नारद-वसिष्ठ-विश्वामित्रादीनामयोनिजानां ब्राह्मणत्वम् । तेषां सवर्णविन्ना+++(=विवाहिता)+++ऽनुत्पन्नत्वात् ।
कृतम्

2022-12-03 07:17 UTC, merged