Corrections
vishvAsa/kalpAntaram pull request #206
Opened 2022-12-14 10:30 UTC by Kamaxi006

2022-12-14 10:35 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## शूद्रस्याहिकमुच्यते
`आह्निकम्`  इति विभागोऽस्त्व् अत्र।

2022-12-14 10:37 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## तपणम्
तर्पणम् इति स्यात् खलु? योजिताः पङ्क्तयश् शुद्धास् स्युः।

2022-12-14 10:38 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## प्रदक्षिणा नमस्काराः
समस्तपदं वेदम्? तथा चेद् रिक्तस्थानं निवार्यताम्, `-` चिह्नं वा तत्स्थाने स्थाप्यताम्।

2022-12-14 10:40 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## प्रयोगः
`### प्रयोगः` इत्यत्र विभागपङ्क्तिः स्यात्। यतो हि नित्यश्राद्धे ऽयम् उपविभागः।

2022-12-14 10:41 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## भोज्यानाः
टङ्कनदोषः

2022-12-14 10:41 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +##
किम् एतत्??

2022-12-14 10:42 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## कीवधर्माः
टङ्कनदोषः

2022-12-14 10:58 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## तपणम्
corrected

2022-12-14 11:03 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## पोडशोपचाराः
corrected

2022-12-14 11:10 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## प्रदक्षिणा नमस्काराः
न स्पष्टं महोदय

2022-12-14 11:12 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## तीर्यमहिमा
corrected

2022-12-14 11:25 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## भोज्यानाः
Corrected

2022-12-14 11:31 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +##
अत्र 'सङ्करजा' इत्येव आगच्छेत् वा?

2022-12-14 11:32 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## कीवधर्माः
Corrected

2022-12-14 11:34 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## स्त्रीधाः
Corrected

2022-12-14 11:45 UTC, vvasuki requested changes

2022-12-14 11:45 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## कीवधर्माः
यथापूर्वम् एव दृश्यते ऽधुनापि।

2022-12-14 11:45 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## स्त्रीधाः
उपर्येव स्त्रीधर्मा इति विभागो वर्तते। कथम् अत्र पुनः?

2022-12-14 11:45 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## प्रयोगः
एवम् अन्यत्रापि शोधयतु।

2022-12-14 11:45 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## प्रदक्षिणा नमस्काराः
मूले किम् अस्तीति चित्रं लिम्पत्व् अत्र। अत्र टङ्कनदोषो ऽस्ति वेति सन्देहः।

2022-12-16 00:59 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +## संस्कारप्रयोगाः
एतत् प्रकरणम् द्वितीय प्रकरणय् उपविभागः। तत्सूचनार्थम् अत्राधिकस्य `#`-चिह्नस्य प्रयोगं कुर्यात्। तेनात्र `### संस्कारप्रयोगाः` इति स्यात्। एवं सर्वत्र शोधयित्वात्र वदतु।

2022-12-16 09:08 UTC, vvasuki requested changes

2022-12-16 09:08 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### जातृकर्म
उट्टङ्कनदोषः

2022-12-16 09:08 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### अथोपवेशनम् ॥
अथशब्दः कुतोऽत्र? सर्वत्र परीक्ष्य परिष्कृत्यात्रैव प्रतिवदतु।

2022-12-16 09:28 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### जातृकर्म
Done

2022-12-16 09:28 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### अथोपवेशनम् ॥
Done

2022-12-16 10:14 UTC, vvasuki requested changes
कृपया https://github.com/vishvAsa/kalpAntaram/pull/206/ इत्यस्मिन् आद्यन्तम् वीक्ष्य, यस्मिन् कस्मिंश्चित् दोषसूत्रे भवत्या उत्तरम् अन्ते न दृश्यते, तत्र तत्र +उत्तराणि लिखतु।

2022-12-16 10:14 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### अथोपवेशनम् ॥
न कृतम् भोः। "सर्वत्र" परीक्ष्य परिष्करोत्व् इत्युक्तौ भवती एकत्रैव परिष्कृतवती। सर्वत्रपरीक्ष्य वदतु।

2022-12-16 12:53 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### अथोपवेशनम् ॥
किम् अपेक्षितम् अस्ति इति स्पष्टं नास्ति महोदय।

2022-12-16 13:08 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### अथोपवेशनम् ॥
अन्यत्रापि शीर्षिकापङ्क्तिषु "अथ"शब्दो निष्कास्यताम्

2022-12-16 13:38 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### अथोपवेशनम् ॥
Done

2022-12-16 14:08 UTC, vvasuki requested changes

2022-12-16 14:08 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### तपणम्
टङ्कनदोषः

2022-12-16 14:08 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### प्रयोगः
तर्पणविभागय् उपविभागोऽयं खलु? तर्हि # इत्यधिकं योजयित्वा "#### " इति करोत्व् अत्र। एवम् अन्यत्रापि (अन्यासि विभागपङ्क्तिषु) शोधयित्वा सूचयत्व् अत्र।

2022-12-16 14:20 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### तपणम्
done

2022-12-16 14:28 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### प्रयोगः
तत् कथं ज्ञातव्यं यत् उपविभागस्य उपविभागः अस्ति वा मुल  प्रकरणस्य उपविभागः अस्ति ??

2022-12-16 14:35 UTC, vvasuki commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### प्रयोगः
प्रयोगशब्दस्य सापेक्षत्वात् सरलम् इह +उपविभागतावगतिः - "कस्य प्रयोग उच्यते?" इति खल्व् आकाङ्क्षोदेति। पूर्वोक्तकर्मण एव "प्रयोग" इति तेनावगम्यते। 

अथवादिमवाक्यानां केषाञ्चन पठनेनापि ज्ञायते।

2022-12-16 14:47 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### प्रयोगः
'आतां स्रानाचा प्रयोग सांगतो' इति वाक्येन सः स्नानस्य प्रयोगः इति ज्ञायते, अतः किंचित् संदेहः।

2022-12-17 04:32 UTC, vvasuki requested changes

2022-12-17 09:27 UTC, Kamaxi006 commented on shUdra-dharmaH/shUdra-kamalAkaraH_sAnuvAdaH.md
> +### तर्पणम्
आं द्विवारम् आगतः अस्ति।

2022-12-17 09:50 UTC, Kamaxi006 commented
केचन् विभागाः प्रकरणे विभाग रूपेण न दर्शिताः किन्तु अनुक्रमणिकायां भिन्नः विभागः इति दर्शितः अस्ति। यथा पृ.स. ३८. तत्र किं योजनीयम्?

2022-12-17 10:06 UTC, vvasuki commented
> केचन् विभागाः प्रकरणे विभाग रूपेण न दर्शिताः किन्तु अनुक्रमणिकायां भिन्नः विभागः इति दर्शितः अस्ति। यथा पृ.स. ३८. तत्र किं योजनीयम्?

tatrānukramaṇikānusārēṇa vibhāgaṁ kalpayituṁ varam bhāti. ēvam tādr̥śēṣv anyēṣu sthānēṣu.

2022-12-19 11:33 UTC, Kamaxi006 commented
यथा भवान् पुर्वम् उक्तवान् अनुक्रमणिकानुसारेण विभागान् योजयितुं शक्यते, किन्तु एका शंका अस्ति यत् अनुक्रमणिकानुसारेण (पृ. स. ५८), शोध कार्ये पङ्क्तिक्रमांकः९६४ इत्यत्र कश्चन 'मङ्लविचारः' नाम्नः विभागः वर्तते किन्तु पुस्तके तत्र केवलं मराठी भाषायां टिप्पणिः एव अस्ति तत्र किम् करणीयम् ?

2022-12-19 11:35 UTC, vvasuki commented
> यथा भवान् पुर्वम् उक्तवान् अनुक्रमणिकानुसारेण विभागान् योजयितुं शक्यते, किन्तु एका शंका अस्ति यत् अनुक्रमणिकानुसारेण (पृ. स. ५८), शोध कार्ये पङ्क्तिक्रमांकः९६४ इत्यत्र कश्चन 'मङ्लविचारः' नाम्नः विभागः वर्तते किन्तु पुस्तके तत्र केवलं मराठी भाषायां टिप्पणिः एव अस्ति तत्र किम् करणीयम् ?

एवं तर्हि तादृशेष्व् अपि स्थलेषु +उचितस्थानेषु विभागपङ्क्तीर् युङ्क्ताम्।

2022-12-19 13:26 UTC, Kamaxi006 commented
द्वे पत्रे पुस्तके न स्तः , पृ. स. १६८, १६९

2022-12-19 16:11 UTC, merged

2022-12-20 09:34 UTC, Kamaxi006 commented
शोधकार्ये प.क्र. १८७ इति footnote इत्यस्य भागः वर्तते तस्य आरंभे मूलम इति लिखितम् अस्ति, तत् तथैव भवतु वा मूलम् तथा टिप्पणि इति केवलं मुख्य भागे ये विभागाः दत्ताः सन्ति तत्र एव भवतु‍ ?