शीर्षकसहितम्
vishvAsa/kalpAntaram pull request #218
Opened 2024-02-02 16:41 UTC by Dhunee

2024-02-03 00:55 UTC, vvasuki requested changes

2024-02-03 00:55 UTC, vvasuki commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +### तत्र स्त्रीणामाह्निकं निरूप्यते ॥
`तत्र स्त्रीणामाह्निकं निरूप्यते ॥` इति वाक्यम् अधो details खण्ड एव भवतु। अत्र तु `### आह्निकम्` इत्य् एतावद् एव शीर्षकं रचयतु। इदं च तन्त्रं सर्वत्रानुसृत्य वदतु।

2024-02-03 00:55 UTC, vvasuki commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +### तिनन्दोऱुम् सॆय्यवेण्डिय कडमैगळ् स्त्रीगळुक्कु तिनन्दोऱुम् सॆय्यवेण्डिय कडमैगळ् निरूबिक्कप्पडुगिण्ड्रन.
द्राविडशीर्षकाः केवलं स्थूलाक्षरैर् दर्शयतु, यथा - 

`**तिनन्दोऱुम् सॆय्यवेण्डिय कडमैगळ् स्त्रीगळुक्कु तिनन्दोऱुम् सॆय्यवेण्डिय कडमैगळ् निरूबिक्कप्पडुगिण्ड्रन**`

इदं च तन्त्रं सर्वत्रानुसृत्य वदतु।

2024-02-03 16:08 UTC, Dhunee commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +### तिनन्दोऱुम् सॆय्यवेण्डिय कडमैगळ् स्त्रीगळुक्कु तिनन्दोऱुम् सॆय्यवेण्डिय कडमैगळ् निरूबिक्कप्पडुगिण्ड्रन.
ओम्

2024-02-03 16:08 UTC, Dhunee commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +### तत्र स्त्रीणामाह्निकं निरूप्यते ॥
ओम्

2024-02-03 17:10 UTC, Dhunee commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +### तिनन्दोऱुम् सॆय्यवेण्डिय कडमैगळ् स्त्रीगळुक्कु तिनन्दोऱुम् सॆय्यवेण्डिय कडमैगळ् निरूबिक्कप्पडुगिण्ड्रन.
अनुसृतम्

2024-02-03 17:10 UTC, Dhunee commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +### तत्र स्त्रीणामाह्निकं निरूप्यते ॥
अनुसृतम्

2024-02-04 02:02 UTC, vvasuki requested changes
आदौ सर्वाः शीर्षिकाः सम्पादयतु।  शिष्टपरिष्कारस् ततः पश्चाद् भवतु।

2024-02-04 02:02 UTC, vvasuki commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +**आचारम्**
उपरि एका रिक्ता पङ्क्तिर् अस्तु।

2024-02-04 02:02 UTC, vvasuki commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +### दन्तधावनम् ।
शीर्षिकासु दण्डो मास्तु।

2024-02-05 16:42 UTC, Dhunee commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +### दन्तधावनम् ।
आम् । निष्कासितः

2024-02-05 16:43 UTC, Dhunee commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +**आचारम्**
अस्ति खलु । अथापि पुनः संयोजिता

2024-02-06 01:18 UTC, vvasuki commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +**आचारम्**
आह्। अस्तु। द्राविडशीर्षिकाः `<details open><summary>द्राविडम्</summary>`  इत्य् आवरणस्यान्तर् एव भवेयुः।  सर्वत्रैवम् परिष्कृत्य सूचयतु।

2024-02-06 11:22 UTC, Dhunee commented on strI-dharma-paddhatiH/sarva-prastutiH/_index.md
> +**आचारम्**
om

2024-02-06 13:51 UTC, merged