Upanayana 10-05-2024
vishvAsa/kalpAntaram pull request #248
Opened 2024-05-10 17:01 UTC by poorvajayant

2024-05-10 21:25 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +The whole procedure of upanayana is more elaborately described in the Āp. gṛ., in Hir. gṛ. and Gobhila. A few points of interest and divergence may be noted here briefly. It is remarkable that Āśv.,
Sasṁkāraratnamālā → Saṁskāraratnamālā

2024-05-10 21:25 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +It is not possible for want of space to show how the great est possible confusion prevails as to the order of the various components of the ceremony of upanayana, But a few striking examples may be g
greatest

2024-05-14 14:29 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +The whole procedure of upanayana is more elaborately described in the Āp. gṛ., in Hir. gṛ. and Gobhila. A few points of interest and divergence may be noted here briefly. It is remarkable that Āśv.,
Sasṁkāraratnamālā → Saṁskāraratnamālā कृतम्।

2024-05-14 14:31 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +It is not possible for want of space to show how the great est possible confusion prevails as to the order of the various components of the ceremony of upanayana, But a few striking examples may be g
greatest इति कृतम्।

2024-05-14 16:17 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +It is not possible for want of space to show how the great est possible confusion prevails as to the order of the various components of the ceremony of upanayana, But a few striking examples may be g
नात्र दृश्यते खलु। कृत्वा, commit+push कृत्वैव कृतम् इति वाच्यम्। अन्यथा परीक्षणं न सम्भवति।

2024-05-14 16:18 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +The whole procedure of upanayana is more elaborately described in the Āp. gṛ., in Hir. gṛ. and Gobhila. A few points of interest and divergence may be noted here briefly. It is remarkable that Āśv.,
नात्र दृश्यते खलु। कृत्वा, commit+push कृत्वैव कृतम् इति वाच्यम्। अन्यथा परीक्षणं न सम्भवति।

2024-05-14 16:25 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> -673. parot TGB TT Pritspur Footat afara repot भवत्येवं यज्ञोपवीती भवति । सग्य बासस्य शिरोऽधाय दक्षिणेसे प्रतिष्ठापयति सम्यं कक्षामन्यवलम्ब भवत्येवं माचीनापीती भवति । पितृपशे व प्राचीनापीती भवति । गोभ
’_’ एतद् चिह्नं निवारितम्।

2024-05-23 12:07 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +The whole procedure of upanayana is more elaborately described in the Āp. gṛ., in Hir. gṛ. and Gobhila. A few points of interest and divergence may be noted here briefly. It is remarkable that Āśv.,
Sasṁkāraratnamālā → Saṁskāraratnamālā इति कृतम्।

2024-05-23 12:07 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +It is not possible for want of space to show how the great est possible confusion prevails as to the order of the various components of the ceremony of upanayana, But a few striking examples may be g
greatest इति कृतम्।

2024-05-23 13:52 UTC, vvasuki requested changes

2024-05-23 13:52 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +(b) Mānava gṛ. (I.22.3) and Kāṭhaka gṛ. (41. 10) prescribe after homa the tasting of curds thrice after repeating the verse 'Dadhikrāṇo akāriṣam'(Ṛg. IV. 39. 6=Tai. S. I. 5. 4. 11).
Dadhikrāvṇo इति स्यात् खलु? कथम् अतावत्यस् तृटयः? द्विः परीक्ष्य हि नुदतु भवती।

2024-05-23 13:52 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +[^680]. नित्यमुत्तरं वासः कार्यम्। अपि वा सूत्रमेवोपवीतार्थे। आप. ध. सू. II. 2. 4. 22-23; सोत्तराच्छादनश्चैव यज्ञोपवीती भुञ्जीत। आप. ध. सू. II. 8. 19. 12; हरदत्त explains "उत्तराच्छादनमुपरिवासः। तेन
पादटिप्पनीष्व् अपि दोषः … यथाङ्गीकृतं नित्यं घण्टां यावद् वा कार्यं कुर्यात् सातत्येन - तदा नैवं विस्मरणं स्यात् …

2024-05-23 15:19 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +(b) Mānava gṛ. (I.22.3) and Kāṭhaka gṛ. (41. 10) prescribe after homa the tasting of curds thrice after repeating the verse 'Dadhikrāṇo akāriṣam'(Ṛg. IV. 39. 6=Tai. S. I. 5. 4. 11).
Dadhikrāvṇo इति कृतम्।

2024-05-23 17:03 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +[^680]. नित्यमुत्तरं वासः कार्यम्। अपि वा सूत्रमेवोपवीतार्थे। आप. ध. सू. II. 2. 4. 22-23; सोत्तराच्छादनश्चैव यज्ञोपवीती भुञ्जीत। आप. ध. सू. II. 8. 19. 12; हरदत्त explains "उत्तराच्छादनमुपरिवासः। तेन
दोषान् निवारितवती।

2024-05-24 02:35 UTC, vvasuki requested changes

2024-05-24 02:35 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +[^682]: The mantra 'यज्ञोपवीतं परमं &c. is cited only in Baud. gṛ. (note 662 above) and in Vaik. (II.5), has certainly a comparatively modern ring about it and is not cited in any well-known ancient
`परमं'` इति `'`-चिह्न-सहितं स्यात् खलु?

2024-05-24 02:35 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +[^680]. नित्यमुत्तरं वासः कार्यम्। अपि वा सूत्रमेवोपवीतार्थे। आप. ध. सू. II. 2. 4. 22-23; सोत्तराच्छादनश्चैव यज्ञोपवीती भुञ्जीत। आप. ध. सू. II. 8. 19. 12; हरदत्त explains "उत्तराच्छादनमुपरिवासः। तेन
कार्यसातत्यविषये च किम् उत्तरम्?

2024-05-25 12:24 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +[^680]. नित्यमुत्तरं वासः कार्यम्। अपि वा सूत्रमेवोपवीतार्थे। आप. ध. सू. II. 2. 4. 22-23; सोत्तराच्छादनश्चैव यज्ञोपवीती भुञ्जीत। आप. ध. सू. II. 8. 19. 12; हरदत्त explains "उत्तराच्छादनमुपरिवासः। तेन
कार्यं सातत्येन करिष्ये।

2024-05-25 14:16 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +[^680]. नित्यमुत्तरं वासः कार्यम्। अपि वा सूत्रमेवोपवीतार्थे। आप. ध. सू. II. 2. 4. 22-23; सोत्तराच्छादनश्चैव यज्ञोपवीती भुञ्जीत। आप. ध. सू. II. 8. 19. 12; हरदत्त explains "उत्तराच्छादनमुपरिवासः। तेन
साधु।

2024-05-25 14:17 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +[^682]: The mantra 'यज्ञोपवीतं परमं &c. is cited only in Baud. gṛ. (note 662 above) and in Vaik. (II.5), has certainly a comparatively modern ring about it and is not cited in any well-known ancient
सदयं screenshot-चित्रं दर्शयतु, येनोचितं विदध्याम्

2024-05-26 02:34 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +[^682]: The mantra 'यज्ञोपवीतं परमं &c. is cited only in Baud. gṛ. (note 662 above) and in Vaik. (II.5), has certainly a comparatively modern ring about it and is not cited in any well-known ancient
![Screenshot 2024-05-26 080041](https://github.com/vishvAsa/kalpAntaram/assets/168164355/b5e02eaf-cd3f-49f1-b5f7-cf581146c977)

2024-05-26 04:19 UTC, vvasuki commented on kANe/v2p1/07_Upanayana.md
> +[^682]: The mantra 'यज्ञोपवीतं परमं &c. is cited only in Baud. gṛ. (note 662 above) and in Vaik. (II.5), has certainly a comparatively modern ring about it and is not cited in any well-known ancient
साधु। तर्हि मूलेऽवर्तमानम् अपि `परमं'` इति सचिह्नं करोतु (लेखकेन तद् इष्टम् भाति)।

2024-05-27 13:55 UTC, poorvajayant commented on kANe/v2p1/07_Upanayana.md
> +[^682]: The mantra 'यज्ञोपवीतं परमं &c. is cited only in Baud. gṛ. (note 662 above) and in Vaik. (II.5), has certainly a comparatively modern ring about it and is not cited in any well-known ancient
परमं' इति सचिह्नं कृतम्।

2024-05-27 14:50 UTC, merged